#!/bin/sh
ssh pi@home.handwoong.com <<EOF
    cd ~/garbage-sorting-backend
    git pull origin dev
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
    . ~/.nvm/nvm.sh
    nvm install 16.14.2
    npm install -g pm2
    npm install -g typescript
    npm install -g ts-node
    yarn install
    tsc
    pm2 restart ecosystem.config.js
    exit
EOF
